Resolve bugs and deprecation warnings
cjb/serverless-webrtc pull request #37
Opened 2019-10-31 15:48 UTC by LeaVerou

Thank you for this fantastic project! This was the only WebRTC resource I actually found approachable.

As many issues have pointed out, this project has gotten out of date and now doesn't work in either Chrome or Firefox and just displays deprecation notices and errors.
This PR attempts to fix most of these.
It now mostly works in both Chrome and Firefox, though displays a stack overflow in Chrome (this PR does not introduce the stack overflow, it just doesn't fix it).
I also removed adapter.js since browsers are now much more interoperable than they used to be back when this was first written. I ported `attachMediaStream` and `reattachMediaStream` directly in serverless-webrtc.js

It needs more work to fix everything but at least it's not completely broken after this PR is merged.

2021-01-01 18:55 UTC, vapier commented on js/serverless-webrtc.js
> +attachMediaStream = function (element, stream) {
should define it as a function instead of declaring a variable.  same with `reattachMediaStream` below.

```js
function attachMediaStream(element, stream) {
```

2021-01-01 19:03 UTC, vapier requested changes

2021-01-01 19:03 UTC, vapier commented on js/serverless-webrtc.js
> +  element.srcObject = stream
these are missing semi-colons at the end of statements

2021-09-03 23:08 UTC, cjb commented
Thanks for the excellent PR, @LeaVerou, and I'm sorry for taking two years to merge it!  I've fixed the "call stack exceeded" error on the main branch now too.

2021-09-03 23:08 UTC, merged